#!/bin/bash
set -e

sudo dnf --refresh update -y
sudo dnf -y install dnf-plugins-core

sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

sudo dnf install -y \
  arandr \
  cmake \
  ctags \
  dmenu \
  docker \
  exa \
  fedora-workstation-repositories \
  feh \
  fuse-sshfs \
  gcc-c++ \
  htop \
  httpie \
  i3 \
  i3lock \
  i3status \
  jq \
  lcov \
  libtool \
  meld \
  syncthing \
  tig \
  tmux \
  util-linux-user \
  neovim \
  NetworkManager \
  xbacklight \
  zsh

sudo dnf config-manager --set-enabled google-chrome
sudo dnf install -y google-chrome-stable

if [[ ! -x "$(command -v keybase)" ]]; then
 sudo dnf install -y https://prerelease.keybase.io/keybase_amd64.rpm
fi

sudo dnf group install -y "Development Libraries" "Development Tools"

# Enable and start docker daemon
if getent group docker; then
  echo "docker group exist"
else
  sudo groupadd docker
fi
sudo usermod -aG docker "$USER"
sudo systemctl enable docker
sudo systemctl start docker

mkdir -p $HOME/.local/bin

# Pip install
pip install --upgrade --user awscli flake8 boto gnupg hvac minio pip consulate

# Zprezto
if [ ! -d "$HOME/.zprezto" ]; then
	git clone --recursive git@github.com:AlexDouze/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi
if [ ! -d "$HOME/.zprezto-contrib" ]; then
  git clone --recursive https://github.com/AlexDouze/prezto-contrib.git "${ZDOTDIR:-$HOME}/.zprezto-contrib"
fi


# Fasd
if [[ ! -x "$(command -v fasd)" ]]; then
  wget https://github.com/clvv/fasd/tarball/1.0.1
  tar xvzf 1.0.1
  rm -f 1.0.1
  cd clvv-fasd-4822024
  sudo make install
  cd ..
  rm -rf clvv-fasd-4822024
fi

# Vim Vundle
if [ ! -d "$HOME/.vim/bundle/vundle" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/vundle
    mkdir -p ~/.vim/colors
fi

# Lastpass
if [[ ! -x "$(command -v lpass)" ]]; then
  git clone https://github.com/lastpass/lastpass-cli.git $HOME/Data/lastpass-cli
fi
TMP=$(pwd)
cd $HOME/Data/lastpass-cli
git pull
make
sudo make install
cd $TMP

# Create syncthing service
mkdir -p $HOME/.config/systemd/user/
sudo wget -O $HOME/.config/systemd/user/syncthing.service https://raw.githubusercontent.com/syncthing/syncthing/master/etc/linux-systemd/user/syncthing.service
systemctl --user enable syncthing.service
systemctl --user start syncthing.service


# Create symlinks for config files
echo "Create symlink for tmux configuration"
ln -sf $PWD/config/tmux.conf $HOME/.tmux.conf

echo "Create symlink for zprezto configuration"
ln -sf $PWD/config/zpreztorc $HOME/.zpreztorc
ln -sf $PWD/config/zshrc $HOME/.zshrc

echo "Create symlink for gitconfig"
ln -sf $PWD/config/gitconfig $HOME/.gitconfig

echo "Create symlink for neovim"
ln -sf $PWD/vim/vimrc $HOME/.config/nvim/init.vim
ln -sf $PWD/vim/vimrc $HOME/.vimrc
ln -sf $PWD/vim/vim $HOME/.vim
nvim +PlugInstall +qall
nvim +UpdateRemotePlugins +qall

echo "Create symlink for i3"
ln -sf $PWD/config/i3-config $HOME/.config/i3/config
ln -sf $PWD/config/i3status.conf $HOME/.i3status.conf

echo "Create symlink for .bin"
ls -sf $PWD/bin $HOME/.bin

chsh -s /bin/zsh

setxkbmap us
