#!/bin/bash
set -e

echo "================="
echo "Updating packages"
sudo dnf --refresh update -y
sudo dnf -y install dnf-plugins-core

echo "================="
echo "Installing packages"
sudo dnf install -y \
  vim \
  arandr \
  autoconf \
  automake \
  cmake \
  code \
  ctags \
  rofi \
  dunst \
  exa \
  fedora-workstation-repositories \
  fuse-sshfs \
  gcc-c++ \
  htop \
  httpie \
  sway \
  swaylock \
  waybar \
  jq \
  keychain \
  lcov \
  libffi-devel \
  libtool \
  libxslt-devel \
  libyaml-devel \
  NetworkManager \
  ncurses-devel \
  openssl-devel \
  alacritty \
  readline-devel \
  scrot \
  syncthing \
  unixODBC-devel \
  util-linux-user \
  zsh


flatpak install flathub com.spotify.Client
flatpak install flathub org.mozilla.firefox

echo "=============="
echo "Install fira code font"
./install_fira_font

mkdir -p $HOME/.local/bin

echo "================="
echo "Installing python packages"
pip3 install --upgrade --user \
  awscli \
  flake8 \
  boto \
  gnupg \
  hvac \
  minio \
  pip \
  consulate \
  pywal \
  python-language-server \
  pyflakes \
  yapf

sudo pip3 install udiskie

echo "================="
echo "Creating symlinks for config files"

echo "Create symlink for zprezto configuration"
rm -rf $HOME/.zshrc.d
rm $HOME/.zpreztorc
rm $HOME/.zshrc
mkdir -p $HOME/.zshrc.d
ln -sf $PWD/config/zpreztorc $HOME/.zpreztorc
ln -sf $PWD/config/zshrc $HOME/.zshrc
ln -sf $PWD/config/yarn-completion.bash $HOME/.zshrc.d/
ln -sf $PWD/config/dircolors-solarized.ansi-light $HOME/.zshrc.d/

echo "Create symlink for gitconfig"
rm $HOME/.gitconfig
ln -sf $PWD/config/gitconfig $HOME/.gitconfig

echo "Create symlink for vim"
rm -rf $HOME/.vim
ln -sf $PWD/vim/vimrc $HOME/.vimrc
ln -sf $PWD/vim/vim $HOME/.vim

echo "Create symlink for sway"
rm -rf $HOME/.config/sway $HOME/.config/compton $HOME/.config/waybar $HOME/.config/dunst
ln -sf $PWD/config/sway $HOME/.config/sway
ln -sf $PWD/config/compton $HOME/.config/compton
ln -sf $PWD/config/waybar $HOME/.config/waybar
ln -sf $PWD/config/dunst $HOME/.config/dunst

echo "Create symlink for .bin"
rm -rf $HOME/.bin
ln -sf $PWD/bin $HOME/.bin

echo "================="
echo "Changing default shell"
chsh -s /bin/zsh
