" Init Plug
if empty(glob('~/.vim/autoload/plug.vim'))
   !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

source ~/.vim/plugins.vim

set expandtab

set linebreak

set list

set mouse=a
set mousefocus

set nobackup
set noswapfile

set number
set numberwidth=5

set smartcase

set splitbelow splitright

set shiftwidth=2
set softtabstop=2
set tabstop=2

set termguicolors
set textwidth=80
set hidden

set wildmenu
set wildmode=list:longest
silent! set wildignorecase

set winwidth=79 winheight=5 winminheight=5 winheight=999

set include=

" Don't redraw the screen during batch execution
set lazyredraw

" Undo
silent !mkdir ~/.vim/undodir > /dev/null 2>&1
set undofile
set undodir=~/.vim/undodir

if exists("+spelllang")
  set spelllang=en_us
endif

command! -bang W w
command! -bang Q q
command! -bang Qa qa
command! -bang Wq wq
command! -bang Wqa wqa
command! -bang QQ qa!
command! -bang WW '!sudo tee % > /dev/null | edit!'
" cnoremap w!! execute 'write !sudo tee % > /dev/null' <bar> edit!

" REST OF FILE CONTAINS MAPPINGS
let mapleader = " "
let maplocalleader = ","

map <leader>s :split<cr>
map <leader>v :vsplit<cr>
map <C-l> <C-W>l
map <C-h> <C-W>h
map <C-j> <C-W>j
map <C-k> <C-W>k

nmap <leader>< [
nmap <leader>> ]
omap <leader>< [
omap <leader>> ]
xmap <leader>< [
xmap <leader>> ]

"" qq to record Q to replay
nmap Q @q
nnoremap Q @q

"" Quickfix
nnoremap ]q :cnext<cr>zz
nnoremap [q :cprev<cr>zz
nnoremap ]l :lnext<cr>zz
nnoremap [l :lprev<cr>zz

" ctrl+l redraws the screen and removes any search highlighting
nnoremap <silent> <leader>l :<C-U>nohlsearch<CR><C-L>
vnoremap <silent> <leader>l :<C-U>nohlsearch<CR>gv<C-L>

" <leader>c Close quickfix
nnoremap <leader>c :cclose<bar>lclose<bar>pclose<cr>

" open files in directory of current file
cnoremap %% <c-r>=expand('%:h').'/'<cr>

" GitGutter
set signcolumn=yes
set updatetime=250

" Emmet completion, rememeber to press `,` after this leader key
let g:user_emmet_leader_key='<C-e>'
let g:user_emmet_settings = {
\  'javascript' : {
\      'extends' : 'jsx',
\  },
\}

" Ag command line option
let g:ag_prg="ag --vimgrep --smart-case"

" FZF
let $FZF_DEFAULT_OPTS .= ' --inline-info'
nnoremap <silent> <leader>p :GFiles<cr>
nnoremap <silent> <leader>o :Files<cr>

let g:fzf_layout = { 'window': 'enew' }
let g:fzf_layout = { 'window': '-tabnew' }
let g:fzf_layout = { 'window': '10split enew' }

" ALE stuff
let g:ale_fix_on_save = 1
let g:ale_completion_enabled = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_list_window_size = 5

let g:ale_elixir_elixir_ls_release = '/elixir-ls'

let g:ale_linters = {
  \ 'javascript': ['eslint', 'flow-language-server'],
  \ 'typescript': ['eslint', 'tslint', 'tsserver'],
  \ 'python': ['pyls'],
  \ 'elixir': ['elixir-ls'],
  \ 'html': []
  \}

let g:ale_fixers = { 'javascript': ['eslint', 'prettier'], 'typescript': ['prettier', 'tsserver'], 'python': [] }

map gd <Plug>(ale_go_to_definition)<CR>
map <c-g>  <Plug>(ale_go_to_definition_in_tab)<CR>
map <F12> <Plug>(ale_find_references)<CR>
map K <Plug>(ale_hover)
nnoremap <leader>S :%s/\<<C-r><C-w>\>/

" Completion
set completeopt=menu,menuone,longest,preview,noinsert
imap <c-f> <c-x><c-f><c-f>
imap <c-space> <c-x><c-o><c-x><c-o>
inoremap <Enter> <C-R>=pumvisible() ? "\<lt>C-y>" : "\<lt>Enter>"<CR>


