
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export SHELL=/usr/bin/zsh
export EDITOR=nvim
export VISUAL=nvim

autoload bashcompinit
bashcompinit

if [[ -s "~/.zshrc.d/yarn-completion.bash" ]]; then
  source "~/.zshrc.d/yarn-completion.bash"
fi

if [[ -s "~/.zshrc.d/kubectl-completion.bash" ]]; then
  source "~/.zshrc.d/kubectl-completion.bash"
fi

eval `dircolors ~/.zshrc.d/dircolors-solarized.ansi-light`

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias dl="cd ~/Downloads"
alias r=ranger

# Get week number
alias week='date +%V'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

alias push="git push --force-with-lease"
alias amend="git ci --amend --no-edit"

reset() {
  git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)
}

alias d=docker
alias dc="docker-compose"
alias yarn=nodejs-yarn

. ${HOME}/projects/shell-utils/zshrc

export PATH="${PATH}:${HOME}/.bin:${HOME}/.yarn/bin:${HOME}/.local/bin/:${HOME}/projects/fleet-management/dev:${HOME}/.cargo/bin:/home/dev/.asdf/shims:/home/dev/.asdf/bin"

export EM_LOCAL_PROJECTS_DIR=${HOME}/projects/

alias g=gws

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /home/nmedda/.asdf/installs/vault/0.9.5/bin/vault vault

# If running from tty1 start sway
if [ "$(tty)" = "/dev/tty1" ]; then
	sway
	exit 0
fi
