
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export SHELL=/usr/bin/zsh
export EDITOR=nvim
export VISUAL=nvim

autoload bashcompinit
bashcompinit

if [[ -s "~/.zshrc.d/yarn-completion.bash" ]]; then
  source "~/.zshrc.d/yarn-completion.bash"
fi

eval `dircolors ~/.zshrc.d/dircolors-solarized.ansi-light`

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias dl="cd ~/Downloads"
alias r=ranger

# Get week number
alias week='date +%V'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

alias push="git push --force-with-lease"
alias ammend="git ci --amend --no-edit"

reset() {
  git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)
}

alias d=docker
alias dc="docker-compose"

create_app() {
  cd /home/session/docker
  d build --network host -t $1 -f $1.Dockerfile .
  cd -
}

slack() {
  d container run --hostname slack --name slack -dti --net=host \
    -v ~/.config/Slack:/home/dev/.config/Slack \
    -v /dev/shm:/dev/shm \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=${DISPLAY} \
    slack
}

alias up="cd ~/projects/session/sitecc && dc up -d"
alias e="cd ~/projects/session/sitecc && dc exec sitecc zsh"

. ${HOME}/projects/shell-utils/zshrc

export PATH="${PATH}:${HOME}/.bin:${HOME}/.yarn/bin:${HOME}/.local/bin/:${HOME}/projects/fleet-management/dev:${HOME}/.cargo/bin"

export EM_LOCAL_PROJECTS_DIR=${HOME}/projects/

alias g=gws

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

