
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export SHELL=/usr/bin/zsh
export EDITOR=nvim
export VISUAL=nvim

autoload bashcompinit
bashcompinit

eval `dircolors ~/.zshrc.d/dircolors-solarized.ansi-light`

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias dl="cd ~/Downloads"

# Get week number
alias week='date +%V'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

alias push="git push --force-with-lease"
alias amend="git ci --amend --no-edit"

reset() {
  git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)
}

alias d=docker

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -U +X bashcompinit && bashcompinit

export PATH=$HOME/.local/bin:$PATH
